name: Docker Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  license-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Scan licenses with Trivy
        uses: aquasecurity/trivy-action@0.14.0
        with:
          scan-type: 'image'
          image-ref: 'alpine/openssl:latest'
          scanners: 'license'
          severity: 'UNKNOWN'
          exit-code: '1'
          format: 'table'
          ignore-unfixed: true

      - name: Save license report
        if: always()
        run: |
          echo "License scan completed at: $(date)" > license-report.txt
          echo "Image: alpine/openssl:latest" >> license-report.txt
          echo "Status: ${{ job.status }}" >> license-report.txt

      - name: Upload license report
        uses: actions/upload-artifact@v4
        with:
          name: license-scan-results
          path: license-report.txt
