name: Docker Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  license-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Strict license scan
        id: trivy-scan
        run: |
          docker pull alpine/openssl:latest
          trivy image --scanners license \
          --format json \
          --exit-code 0 \
          alpine/openssl:latest > trivy-results.json
          
          if [ $(jq '.Results[].Licenses | length' trivy-results.json) -gt 0 ]; then
            echo "::error::Found licenses in image!"
            exit 1
          fi

      - name: Generate license report
        if: always()
        run: |
          echo "=== License Scan Report ===" > report.txt
          echo "Image: alpine/openssl:latest" >> report.txt
          echo "Scan date: $(date)" >> report.txt
          echo "Licenses found: $([ ${{ steps.trivy-scan.outcome }} == 'failure' ] && echo "YES" || echo "NO")" >> report.txt
          cat trivy-results.json | jq -r '.Results[].Licenses[].Name' >> report.txt

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: license-report
          path: |
            report.txt
            trivy-results.json
