name: Docker Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  license-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Scan for licenses
        uses: aquasecurity/trivy-action@0.14.0
        id: trivy-scan
        with:
          scan-type: 'image'
          image-ref: 'alpine/openssl:latest'
          scanners: 'license'
          format: 'json'
          exit-code: '0'
          ignore-unfixed: true

      - name: Check licenses
        if: always()
        run: |
          if [ $(jq -e '.Results[0].Licenses | length > 0' trivy-results.json) == "true" ]; then
            echo "::error::Found licenses:"
            jq -r '.Results[0].Licenses[].Name' trivy-results.json | while read license; do
              echo " - $license"
            done
            exit 1
          else
            echo "No licenses found"
          fi

      - name: Generate report
        if: always()
        run: |
          echo "=== License Scan Report ===" > report.txt
          echo "Image: alpine/openssl:latest" >> report.txt
          echo "Status: $([ ${{ steps.trivy-scan.outcome }} == 'failure' ] && echo "FAILED" || echo "PASSED")" >> report.txt
          echo "Licenses found:" >> report.txt
          jq -r '.Results[0].Licenses[].Name' trivy-results.json >> report.txt

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: license-scan-results
          path: |
            report.txt
            trivy-results.json
